### ISSUE TITLE
What a lucky day I can find this interesting repo!!

### ISSUE THREAD

**Issue by CodingCatMountain** [cvg25/tossingbot#1]
@cvg25 Thanks a lot of sharing this repo.  The original paper is interesting when I was a graduate student. Now I have been an employee  in a robotic company. I still want to learn more about simulation for robotic manipulation task. And I found this repo. Thank you again! @cvg25.

**Comment by CodingCatMountain** [comment]
HHH, I hope this issue will not bother you. And I will close this issue now.

**Comment by cvg25** [comment]
Hello @CodingCatMountain, 
Thanks for writing, I felt the same, and I thought it was a good idea to try and implement it from scratch as a fun weekend project. 

It is my attempt to replicate the paper description, as close as possible, however in the paper there is some missing information that I tried my best to guess. 

I feel like the simulation is a bit unstable sometimes which often causes degraded results, and could be tuned to further improve the current results which often plateau at 70% throwing success. For instance, the gripper sometimes fails to hold up objects or they remain sticked to the gripper finger when releasing for throwing... if you find better hyperparms for the simulation of both objects and gripper, feel free to suggest a PR. 😄 

Maybe the original author @andyzeng can shed some light here! haha

Cheer and enjoy,
Carlos
